// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// DeleteNumberReader is a Reader for the DeleteNumber structure.
type DeleteNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteNumberNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteNumberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteNumberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteNumberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteNumberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNumberNoContent creates a DeleteNumberNoContent with default headers values
func NewDeleteNumberNoContent() *DeleteNumberNoContent {
	return &DeleteNumberNoContent{}
}

/*DeleteNumberNoContent handles this case with default header values.

Deleted
*/
type DeleteNumberNoContent struct {
}

func (o *DeleteNumberNoContent) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNoContent ", 204)
}

func (o *DeleteNumberNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNumberUnauthorized creates a DeleteNumberUnauthorized with default headers values
func NewDeleteNumberUnauthorized() *DeleteNumberUnauthorized {
	return &DeleteNumberUnauthorized{}
}

/*DeleteNumberUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type DeleteNumberUnauthorized struct {
	WWWAuthenticate string
}

func (o *DeleteNumberUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberUnauthorized ", 401)
}

func (o *DeleteNumberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewDeleteNumberForbidden creates a DeleteNumberForbidden with default headers values
func NewDeleteNumberForbidden() *DeleteNumberForbidden {
	return &DeleteNumberForbidden{}
}

/*DeleteNumberForbidden handles this case with default header values.

User not authorized or blocked
*/
type DeleteNumberForbidden struct {
	Payload *DeleteNumberForbiddenBody
}

func (o *DeleteNumberForbidden) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberForbidden  %+v", 403, o.Payload)
}

func (o *DeleteNumberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteNumberForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNumberNotFound creates a DeleteNumberNotFound with default headers values
func NewDeleteNumberNotFound() *DeleteNumberNotFound {
	return &DeleteNumberNotFound{}
}

/*DeleteNumberNotFound handles this case with default header values.

Resource not found
*/
type DeleteNumberNotFound struct {
	Payload *DeleteNumberNotFoundBody
}

func (o *DeleteNumberNotFound) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNotFound  %+v", 404, o.Payload)
}

func (o *DeleteNumberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteNumberNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNumberInternalServerError creates a DeleteNumberInternalServerError with default headers values
func NewDeleteNumberInternalServerError() *DeleteNumberInternalServerError {
	return &DeleteNumberInternalServerError{}
}

/*DeleteNumberInternalServerError handles this case with default header values.

Error
*/
type DeleteNumberInternalServerError struct {
	Payload *DeleteNumberInternalServerErrorBody
}

func (o *DeleteNumberInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteNumberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(DeleteNumberInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*DeleteNumberForbiddenBody UnauthorizedResponse
swagger:model DeleteNumberForbiddenBody
*/
type DeleteNumberForbiddenBody struct {

	// error
	Error *DeleteNumberForbiddenBodyError `json:"error,omitempty"`

	// meta
	Meta *models.MetaResponse `json:"meta,omitempty"`
}

// Validate validates this delete number forbidden body
func (o *DeleteNumberForbiddenBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberForbiddenBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberForbidden" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *DeleteNumberForbiddenBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberForbidden" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberForbiddenBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberForbiddenBody) UnmarshalBinary(b []byte) error {
	var res DeleteNumberForbiddenBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteNumberForbiddenBodyError delete number forbidden body error
swagger:model DeleteNumberForbiddenBodyError
*/
type DeleteNumberForbiddenBodyError struct {

	// Forbidden Message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete number forbidden body error
func (o *DeleteNumberForbiddenBodyError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberForbiddenBodyError) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteNumberForbidden"+"."+"error"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberForbiddenBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberForbiddenBodyError) UnmarshalBinary(b []byte) error {
	var res DeleteNumberForbiddenBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteNumberInternalServerErrorBody ErrorResponse
swagger:model DeleteNumberInternalServerErrorBody
*/
type DeleteNumberInternalServerErrorBody struct {

	// error
	Error *DeleteNumberInternalServerErrorBodyError `json:"error,omitempty"`

	// meta
	Meta *models.MetaResponse `json:"meta,omitempty"`
}

// Validate validates this delete number internal server error body
func (o *DeleteNumberInternalServerErrorBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberInternalServerErrorBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberInternalServerError" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *DeleteNumberInternalServerErrorBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberInternalServerError" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberInternalServerErrorBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberInternalServerErrorBody) UnmarshalBinary(b []byte) error {
	var res DeleteNumberInternalServerErrorBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteNumberInternalServerErrorBodyError delete number internal server error body error
swagger:model DeleteNumberInternalServerErrorBodyError
*/
type DeleteNumberInternalServerErrorBodyError struct {

	// Error Message
	// Required: true
	Message *string `json:"message"`

	// Parameter the error message is related to
	// `null` is the error is generic
	//
	Param *string `json:"param,omitempty"`
}

// Validate validates this delete number internal server error body error
func (o *DeleteNumberInternalServerErrorBodyError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberInternalServerErrorBodyError) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteNumberInternalServerError"+"."+"error"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberInternalServerErrorBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberInternalServerErrorBodyError) UnmarshalBinary(b []byte) error {
	var res DeleteNumberInternalServerErrorBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteNumberNotFoundBody NotFoundResponse
swagger:model DeleteNumberNotFoundBody
*/
type DeleteNumberNotFoundBody struct {

	// error
	Error *DeleteNumberNotFoundBodyError `json:"error,omitempty"`

	// meta
	Meta *models.MetaResponse `json:"meta,omitempty"`
}

// Validate validates this delete number not found body
func (o *DeleteNumberNotFoundBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateError(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateMeta(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberNotFoundBody) validateError(formats strfmt.Registry) error {

	if swag.IsZero(o.Error) { // not required
		return nil
	}

	if o.Error != nil {
		if err := o.Error.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberNotFound" + "." + "error")
			}
			return err
		}
	}

	return nil
}

func (o *DeleteNumberNotFoundBody) validateMeta(formats strfmt.Registry) error {

	if swag.IsZero(o.Meta) { // not required
		return nil
	}

	if o.Meta != nil {
		if err := o.Meta.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("deleteNumberNotFound" + "." + "meta")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberNotFoundBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberNotFoundBody) UnmarshalBinary(b []byte) error {
	var res DeleteNumberNotFoundBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*DeleteNumberNotFoundBodyError delete number not found body error
swagger:model DeleteNumberNotFoundBodyError
*/
type DeleteNumberNotFoundBodyError struct {

	// Error Message
	// Required: true
	Message *string `json:"message"`
}

// Validate validates this delete number not found body error
func (o *DeleteNumberNotFoundBodyError) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateMessage(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *DeleteNumberNotFoundBodyError) validateMessage(formats strfmt.Registry) error {

	if err := validate.Required("deleteNumberNotFound"+"."+"error"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *DeleteNumberNotFoundBodyError) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *DeleteNumberNotFoundBodyError) UnmarshalBinary(b []byte) error {
	var res DeleteNumberNotFoundBodyError
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
