// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// DeleteNumberNumReader is a Reader for the DeleteNumberNum structure.
type DeleteNumberNumReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteNumberNumReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteNumberNumNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteNumberNumUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteNumberNumForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteNumberNumNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteNumberNumInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteNumberNumNoContent creates a DeleteNumberNumNoContent with default headers values
func NewDeleteNumberNumNoContent() *DeleteNumberNumNoContent {
	return &DeleteNumberNumNoContent{}
}

/*DeleteNumberNumNoContent handles this case with default header values.

Deleted
*/
type DeleteNumberNumNoContent struct {
}

func (o *DeleteNumberNumNoContent) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNumNoContent ", 204)
}

func (o *DeleteNumberNumNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteNumberNumUnauthorized creates a DeleteNumberNumUnauthorized with default headers values
func NewDeleteNumberNumUnauthorized() *DeleteNumberNumUnauthorized {
	return &DeleteNumberNumUnauthorized{}
}

/*DeleteNumberNumUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type DeleteNumberNumUnauthorized struct {
	WWWAuthenticate string
}

func (o *DeleteNumberNumUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNumUnauthorized ", 401)
}

func (o *DeleteNumberNumUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewDeleteNumberNumForbidden creates a DeleteNumberNumForbidden with default headers values
func NewDeleteNumberNumForbidden() *DeleteNumberNumForbidden {
	return &DeleteNumberNumForbidden{}
}

/*DeleteNumberNumForbidden handles this case with default header values.

User not authorized or blocked
*/
type DeleteNumberNumForbidden struct {
	Payload *models.DeleteNumberNumForbiddenBody
}

func (o *DeleteNumberNumForbidden) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNumForbidden  %+v", 403, o.Payload)
}

func (o *DeleteNumberNumForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteNumberNumForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNumberNumNotFound creates a DeleteNumberNumNotFound with default headers values
func NewDeleteNumberNumNotFound() *DeleteNumberNumNotFound {
	return &DeleteNumberNumNotFound{}
}

/*DeleteNumberNumNotFound handles this case with default header values.

Resource not found
*/
type DeleteNumberNumNotFound struct {
	Payload *models.DeleteNumberNumNotFoundBody
}

func (o *DeleteNumberNumNotFound) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNumNotFound  %+v", 404, o.Payload)
}

func (o *DeleteNumberNumNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteNumberNumNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteNumberNumInternalServerError creates a DeleteNumberNumInternalServerError with default headers values
func NewDeleteNumberNumInternalServerError() *DeleteNumberNumInternalServerError {
	return &DeleteNumberNumInternalServerError{}
}

/*DeleteNumberNumInternalServerError handles this case with default header values.

Error
*/
type DeleteNumberNumInternalServerError struct {
	Payload *models.DeleteNumberNumInternalServerErrorBody
}

func (o *DeleteNumberNumInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /number/{num}/][%d] deleteNumberNumInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteNumberNumInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteNumberNumInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
