// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNumberParams creates a new GetNumberParams object
// with the default values initialized.
func NewGetNumberParams() *GetNumberParams {
	var (
		aPIVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetNumberParams{
		APIVersion: &aPIVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNumberParamsWithTimeout creates a new GetNumberParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNumberParamsWithTimeout(timeout time.Duration) *GetNumberParams {
	var (
		aPIVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetNumberParams{
		APIVersion: &aPIVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		timeout: timeout,
	}
}

// NewGetNumberParamsWithContext creates a new GetNumberParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNumberParamsWithContext(ctx context.Context) *GetNumberParams {
	var (
		apiVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetNumberParams{
		APIVersion: &apiVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		Context: ctx,
	}
}

// NewGetNumberParamsWithHTTPClient creates a new GetNumberParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNumberParamsWithHTTPClient(client *http.Client) *GetNumberParams {
	var (
		apiVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetNumberParams{
		APIVersion: &apiVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,
		HTTPClient: client,
	}
}

/*GetNumberParams contains all the parameters to send to the API endpoint
for the get number operation typically these are written to a http.Request
*/
type GetNumberParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion *string
	/*Contains
	  Filter by numbers which contain this value

	*/
	Contains *string
	/*Country
	  Filter by country ISO

	*/
	Country *string
	/*Limit
	  The numbers of items to return.

	*/
	Limit *int64
	/*NumberType
	  Filter by number type: fixed, mobile, tollfree

	*/
	NumberType []string
	/*Offset
	  The number of items to skip before starting to collect the result set.

	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get number params
func (o *GetNumberParams) WithTimeout(timeout time.Duration) *GetNumberParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get number params
func (o *GetNumberParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get number params
func (o *GetNumberParams) WithContext(ctx context.Context) *GetNumberParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get number params
func (o *GetNumberParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get number params
func (o *GetNumberParams) WithHTTPClient(client *http.Client) *GetNumberParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get number params
func (o *GetNumberParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get number params
func (o *GetNumberParams) WithAPIVersion(aPIVersion *string) *GetNumberParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get number params
func (o *GetNumberParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithContains adds the contains to the get number params
func (o *GetNumberParams) WithContains(contains *string) *GetNumberParams {
	o.SetContains(contains)
	return o
}

// SetContains adds the contains to the get number params
func (o *GetNumberParams) SetContains(contains *string) {
	o.Contains = contains
}

// WithCountry adds the country to the get number params
func (o *GetNumberParams) WithCountry(country *string) *GetNumberParams {
	o.SetCountry(country)
	return o
}

// SetCountry adds the country to the get number params
func (o *GetNumberParams) SetCountry(country *string) {
	o.Country = country
}

// WithLimit adds the limit to the get number params
func (o *GetNumberParams) WithLimit(limit *int64) *GetNumberParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get number params
func (o *GetNumberParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithNumberType adds the numberType to the get number params
func (o *GetNumberParams) WithNumberType(numberType []string) *GetNumberParams {
	o.SetNumberType(numberType)
	return o
}

// SetNumberType adds the numberType to the get number params
func (o *GetNumberParams) SetNumberType(numberType []string) {
	o.NumberType = numberType
}

// WithOffset adds the offset to the get number params
func (o *GetNumberParams) WithOffset(offset *int64) *GetNumberParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get number params
func (o *GetNumberParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetNumberParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param api-version
		if err := r.SetHeaderParam("api-version", *o.APIVersion); err != nil {
			return err
		}

	}

	if o.Contains != nil {

		// query param contains
		var qrContains string
		if o.Contains != nil {
			qrContains = *o.Contains
		}
		qContains := qrContains
		if qContains != "" {
			if err := r.SetQueryParam("contains", qContains); err != nil {
				return err
			}
		}

	}

	if o.Country != nil {

		// query param country
		var qrCountry string
		if o.Country != nil {
			qrCountry = *o.Country
		}
		qCountry := qrCountry
		if qCountry != "" {
			if err := r.SetQueryParam("country", qCountry); err != nil {
				return err
			}
		}

	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	valuesNumberType := o.NumberType

	joinedNumberType := swag.JoinByFormat(valuesNumberType, "csv")
	// query array param number_type
	if err := r.SetQueryParam("number_type", joinedNumberType...); err != nil {
		return err
	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
