// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNumberDetailsParams creates a new GetNumberDetailsParams object
// with the default values initialized.
func NewGetNumberDetailsParams() *GetNumberDetailsParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetNumberDetailsParams{
		APIVersion: aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNumberDetailsParamsWithTimeout creates a new GetNumberDetailsParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNumberDetailsParamsWithTimeout(timeout time.Duration) *GetNumberDetailsParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetNumberDetailsParams{
		APIVersion: aPIVersionDefault,

		timeout: timeout,
	}
}

// NewGetNumberDetailsParamsWithContext creates a new GetNumberDetailsParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNumberDetailsParamsWithContext(ctx context.Context) *GetNumberDetailsParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetNumberDetailsParams{
		APIVersion: apiVersionDefault,

		Context: ctx,
	}
}

// NewGetNumberDetailsParamsWithHTTPClient creates a new GetNumberDetailsParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNumberDetailsParamsWithHTTPClient(client *http.Client) *GetNumberDetailsParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetNumberDetailsParams{
		APIVersion: apiVersionDefault,
		HTTPClient: client,
	}
}

/*GetNumberDetailsParams contains all the parameters to send to the API endpoint
for the get number details operation typically these are written to a http.Request
*/
type GetNumberDetailsParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion string
	/*Num
	  Number for which details need to be fetched

	*/
	Num int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get number details params
func (o *GetNumberDetailsParams) WithTimeout(timeout time.Duration) *GetNumberDetailsParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get number details params
func (o *GetNumberDetailsParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get number details params
func (o *GetNumberDetailsParams) WithContext(ctx context.Context) *GetNumberDetailsParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get number details params
func (o *GetNumberDetailsParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get number details params
func (o *GetNumberDetailsParams) WithHTTPClient(client *http.Client) *GetNumberDetailsParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get number details params
func (o *GetNumberDetailsParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get number details params
func (o *GetNumberDetailsParams) WithAPIVersion(aPIVersion string) *GetNumberDetailsParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get number details params
func (o *GetNumberDetailsParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithNum adds the num to the get number details params
func (o *GetNumberDetailsParams) WithNum(num int64) *GetNumberDetailsParams {
	o.SetNum(num)
	return o
}

// SetNum adds the num to the get number details params
func (o *GetNumberDetailsParams) SetNum(num int64) {
	o.Num = num
}

// WriteToRequest writes these params to a swagger request
func (o *GetNumberDetailsParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param api-version
	if err := r.SetHeaderParam("api-version", o.APIVersion); err != nil {
		return err
	}

	// path param num
	if err := r.SetPathParam("num", swag.FormatInt64(o.Num)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
