// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetNumberNumParams creates a new GetNumberNumParams object
// with the default values initialized.
func NewGetNumberNumParams() *GetNumberNumParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetNumberNumParams{
		APIVersion: &aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetNumberNumParamsWithTimeout creates a new GetNumberNumParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetNumberNumParamsWithTimeout(timeout time.Duration) *GetNumberNumParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetNumberNumParams{
		APIVersion: &aPIVersionDefault,

		timeout: timeout,
	}
}

// NewGetNumberNumParamsWithContext creates a new GetNumberNumParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetNumberNumParamsWithContext(ctx context.Context) *GetNumberNumParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetNumberNumParams{
		APIVersion: &apiVersionDefault,

		Context: ctx,
	}
}

// NewGetNumberNumParamsWithHTTPClient creates a new GetNumberNumParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetNumberNumParamsWithHTTPClient(client *http.Client) *GetNumberNumParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetNumberNumParams{
		APIVersion: &apiVersionDefault,
		HTTPClient: client,
	}
}

/*GetNumberNumParams contains all the parameters to send to the API endpoint
for the get number num operation typically these are written to a http.Request
*/
type GetNumberNumParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion *string
	/*Num
	  Number for which details need to be fetched

	*/
	Num int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get number num params
func (o *GetNumberNumParams) WithTimeout(timeout time.Duration) *GetNumberNumParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get number num params
func (o *GetNumberNumParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get number num params
func (o *GetNumberNumParams) WithContext(ctx context.Context) *GetNumberNumParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get number num params
func (o *GetNumberNumParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get number num params
func (o *GetNumberNumParams) WithHTTPClient(client *http.Client) *GetNumberNumParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get number num params
func (o *GetNumberNumParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get number num params
func (o *GetNumberNumParams) WithAPIVersion(aPIVersion *string) *GetNumberNumParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get number num params
func (o *GetNumberNumParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithNum adds the num to the get number num params
func (o *GetNumberNumParams) WithNum(num int64) *GetNumberNumParams {
	o.SetNum(num)
	return o
}

// SetNum adds the num to the get number num params
func (o *GetNumberNumParams) SetNum(num int64) {
	o.Num = num
}

// WriteToRequest writes these params to a swagger request
func (o *GetNumberNumParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param api-version
		if err := r.SetHeaderParam("api-version", *o.APIVersion); err != nil {
			return err
		}

	}

	// path param num
	if err := r.SetPathParam("num", swag.FormatInt64(o.Num)); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
