// Code generated by go-swagger; DO NOT EDIT.

package number

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// RentNumberReader is a Reader for the RentNumber structure.
type RentNumberReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *RentNumberReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewRentNumberCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewRentNumberBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewRentNumberUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 402:
		result := NewRentNumberPaymentRequired()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewRentNumberForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewRentNumberNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewRentNumberInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewRentNumberCreated creates a RentNumberCreated with default headers values
func NewRentNumberCreated() *RentNumberCreated {
	return &RentNumberCreated{}
}

/*RentNumberCreated handles this case with default header values.

Number data
*/
type RentNumberCreated struct {
	Payload *models.RentNumberCreatedBody
}

func (o *RentNumberCreated) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberCreated  %+v", 201, o.Payload)
}

func (o *RentNumberCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRentNumberBadRequest creates a RentNumberBadRequest with default headers values
func NewRentNumberBadRequest() *RentNumberBadRequest {
	return &RentNumberBadRequest{}
}

/*RentNumberBadRequest handles this case with default header values.

Error
*/
type RentNumberBadRequest struct {
	Payload *models.RentNumberBadRequestBody
}

func (o *RentNumberBadRequest) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberBadRequest  %+v", 400, o.Payload)
}

func (o *RentNumberBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRentNumberUnauthorized creates a RentNumberUnauthorized with default headers values
func NewRentNumberUnauthorized() *RentNumberUnauthorized {
	return &RentNumberUnauthorized{}
}

/*RentNumberUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type RentNumberUnauthorized struct {
	WWWAuthenticate string
}

func (o *RentNumberUnauthorized) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberUnauthorized ", 401)
}

func (o *RentNumberUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewRentNumberPaymentRequired creates a RentNumberPaymentRequired with default headers values
func NewRentNumberPaymentRequired() *RentNumberPaymentRequired {
	return &RentNumberPaymentRequired{}
}

/*RentNumberPaymentRequired handles this case with default header values.

Insufficient Balance Error
*/
type RentNumberPaymentRequired struct {
	Payload *models.RentNumberPaymentRequiredBody
}

func (o *RentNumberPaymentRequired) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberPaymentRequired  %+v", 402, o.Payload)
}

func (o *RentNumberPaymentRequired) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberPaymentRequiredBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRentNumberForbidden creates a RentNumberForbidden with default headers values
func NewRentNumberForbidden() *RentNumberForbidden {
	return &RentNumberForbidden{}
}

/*RentNumberForbidden handles this case with default header values.

User not authorized or blocked
*/
type RentNumberForbidden struct {
	Payload *models.RentNumberForbiddenBody
}

func (o *RentNumberForbidden) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberForbidden  %+v", 403, o.Payload)
}

func (o *RentNumberForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRentNumberNotFound creates a RentNumberNotFound with default headers values
func NewRentNumberNotFound() *RentNumberNotFound {
	return &RentNumberNotFound{}
}

/*RentNumberNotFound handles this case with default header values.

Resource not found
*/
type RentNumberNotFound struct {
	Payload *models.RentNumberNotFoundBody
}

func (o *RentNumberNotFound) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberNotFound  %+v", 404, o.Payload)
}

func (o *RentNumberNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewRentNumberInternalServerError creates a RentNumberInternalServerError with default headers values
func NewRentNumberInternalServerError() *RentNumberInternalServerError {
	return &RentNumberInternalServerError{}
}

/*RentNumberInternalServerError handles this case with default header values.

Error
*/
type RentNumberInternalServerError struct {
	Payload *models.RentNumberInternalServerErrorBody
}

func (o *RentNumberInternalServerError) Error() string {
	return fmt.Sprintf("[POST /number/][%d] rentNumberInternalServerError  %+v", 500, o.Payload)
}

func (o *RentNumberInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.RentNumberInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
