// Code generated by go-swagger; DO NOT EDIT.

package message

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetMessageByIDParams creates a new GetMessageByIDParams object
// with the default values initialized.
func NewGetMessageByIDParams() *GetMessageByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetMessageByIDParams{
		APIVersion: &aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetMessageByIDParamsWithTimeout creates a new GetMessageByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetMessageByIDParamsWithTimeout(timeout time.Duration) *GetMessageByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetMessageByIDParams{
		APIVersion: &aPIVersionDefault,

		timeout: timeout,
	}
}

// NewGetMessageByIDParamsWithContext creates a new GetMessageByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetMessageByIDParamsWithContext(ctx context.Context) *GetMessageByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetMessageByIDParams{
		APIVersion: &apiVersionDefault,

		Context: ctx,
	}
}

// NewGetMessageByIDParamsWithHTTPClient creates a new GetMessageByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetMessageByIDParamsWithHTTPClient(client *http.Client) *GetMessageByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetMessageByIDParams{
		APIVersion: &apiVersionDefault,
		HTTPClient: client,
	}
}

/*GetMessageByIDParams contains all the parameters to send to the API endpoint
for the get message by Id operation typically these are written to a http.Request
*/
type GetMessageByIDParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion *string
	/*UID
	  Alphanumeric ID of the message to get.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get message by Id params
func (o *GetMessageByIDParams) WithTimeout(timeout time.Duration) *GetMessageByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get message by Id params
func (o *GetMessageByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get message by Id params
func (o *GetMessageByIDParams) WithContext(ctx context.Context) *GetMessageByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get message by Id params
func (o *GetMessageByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get message by Id params
func (o *GetMessageByIDParams) WithHTTPClient(client *http.Client) *GetMessageByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get message by Id params
func (o *GetMessageByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get message by Id params
func (o *GetMessageByIDParams) WithAPIVersion(aPIVersion *string) *GetMessageByIDParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get message by Id params
func (o *GetMessageByIDParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithUID adds the uid to the get message by Id params
func (o *GetMessageByIDParams) WithUID(uid string) *GetMessageByIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the get message by Id params
func (o *GetMessageByIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *GetMessageByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param api-version
		if err := r.SetHeaderParam("api-version", *o.APIVersion); err != nil {
			return err
		}

	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
