// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// CreateWebhookReader is a Reader for the CreateWebhook structure.
type CreateWebhookReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateWebhookReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateWebhookCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateWebhookBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateWebhookUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateWebhookForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateWebhookInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateWebhookCreated creates a CreateWebhookCreated with default headers values
func NewCreateWebhookCreated() *CreateWebhookCreated {
	return &CreateWebhookCreated{}
}

/*CreateWebhookCreated handles this case with default header values.

Webhook data
*/
type CreateWebhookCreated struct {
	Payload *models.CreateWebhookCreatedBody
}

func (o *CreateWebhookCreated) Error() string {
	return fmt.Sprintf("[POST /webhook/][%d] createWebhookCreated  %+v", 201, o.Payload)
}

func (o *CreateWebhookCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateWebhookCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWebhookBadRequest creates a CreateWebhookBadRequest with default headers values
func NewCreateWebhookBadRequest() *CreateWebhookBadRequest {
	return &CreateWebhookBadRequest{}
}

/*CreateWebhookBadRequest handles this case with default header values.

Error
*/
type CreateWebhookBadRequest struct {
	Payload *models.CreateWebhookBadRequestBody
}

func (o *CreateWebhookBadRequest) Error() string {
	return fmt.Sprintf("[POST /webhook/][%d] createWebhookBadRequest  %+v", 400, o.Payload)
}

func (o *CreateWebhookBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateWebhookBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWebhookUnauthorized creates a CreateWebhookUnauthorized with default headers values
func NewCreateWebhookUnauthorized() *CreateWebhookUnauthorized {
	return &CreateWebhookUnauthorized{}
}

/*CreateWebhookUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type CreateWebhookUnauthorized struct {
	WWWAuthenticate string
}

func (o *CreateWebhookUnauthorized) Error() string {
	return fmt.Sprintf("[POST /webhook/][%d] createWebhookUnauthorized ", 401)
}

func (o *CreateWebhookUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewCreateWebhookForbidden creates a CreateWebhookForbidden with default headers values
func NewCreateWebhookForbidden() *CreateWebhookForbidden {
	return &CreateWebhookForbidden{}
}

/*CreateWebhookForbidden handles this case with default header values.

User not authorized or blocked
*/
type CreateWebhookForbidden struct {
	Payload *models.CreateWebhookForbiddenBody
}

func (o *CreateWebhookForbidden) Error() string {
	return fmt.Sprintf("[POST /webhook/][%d] createWebhookForbidden  %+v", 403, o.Payload)
}

func (o *CreateWebhookForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateWebhookForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateWebhookInternalServerError creates a CreateWebhookInternalServerError with default headers values
func NewCreateWebhookInternalServerError() *CreateWebhookInternalServerError {
	return &CreateWebhookInternalServerError{}
}

/*CreateWebhookInternalServerError handles this case with default header values.

Error
*/
type CreateWebhookInternalServerError struct {
	Payload *models.CreateWebhookInternalServerErrorBody
}

func (o *CreateWebhookInternalServerError) Error() string {
	return fmt.Sprintf("[POST /webhook/][%d] createWebhookInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateWebhookInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateWebhookInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
