// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewDeleteWebhookByIDParams creates a new DeleteWebhookByIDParams object
// with the default values initialized.
func NewDeleteWebhookByIDParams() *DeleteWebhookByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &DeleteWebhookByIDParams{
		APIVersion: aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewDeleteWebhookByIDParamsWithTimeout creates a new DeleteWebhookByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewDeleteWebhookByIDParamsWithTimeout(timeout time.Duration) *DeleteWebhookByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &DeleteWebhookByIDParams{
		APIVersion: aPIVersionDefault,

		timeout: timeout,
	}
}

// NewDeleteWebhookByIDParamsWithContext creates a new DeleteWebhookByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewDeleteWebhookByIDParamsWithContext(ctx context.Context) *DeleteWebhookByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &DeleteWebhookByIDParams{
		APIVersion: apiVersionDefault,

		Context: ctx,
	}
}

// NewDeleteWebhookByIDParamsWithHTTPClient creates a new DeleteWebhookByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewDeleteWebhookByIDParamsWithHTTPClient(client *http.Client) *DeleteWebhookByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &DeleteWebhookByIDParams{
		APIVersion: apiVersionDefault,
		HTTPClient: client,
	}
}

/*DeleteWebhookByIDParams contains all the parameters to send to the API endpoint
for the delete webhook by Id operation typically these are written to a http.Request
*/
type DeleteWebhookByIDParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion string
	/*UID
	  Alphanumeric ID of the webhook to be deleted.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) WithTimeout(timeout time.Duration) *DeleteWebhookByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) WithContext(ctx context.Context) *DeleteWebhookByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) WithHTTPClient(client *http.Client) *DeleteWebhookByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) WithAPIVersion(aPIVersion string) *DeleteWebhookByIDParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithUID adds the uid to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) WithUID(uid string) *DeleteWebhookByIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the delete webhook by Id params
func (o *DeleteWebhookByIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *DeleteWebhookByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param api-version
	if err := r.SetHeaderParam("api-version", o.APIVersion); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
