// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// DeleteWebhookByIDReader is a Reader for the DeleteWebhookByID structure.
type DeleteWebhookByIDReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *DeleteWebhookByIDReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 204:
		result := NewDeleteWebhookByIDNoContent()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewDeleteWebhookByIDUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewDeleteWebhookByIDForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 404:
		result := NewDeleteWebhookByIDNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewDeleteWebhookByIDInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewDeleteWebhookByIDNoContent creates a DeleteWebhookByIDNoContent with default headers values
func NewDeleteWebhookByIDNoContent() *DeleteWebhookByIDNoContent {
	return &DeleteWebhookByIDNoContent{}
}

/*DeleteWebhookByIDNoContent handles this case with default header values.

Deleted
*/
type DeleteWebhookByIDNoContent struct {
}

func (o *DeleteWebhookByIDNoContent) Error() string {
	return fmt.Sprintf("[DELETE /webhook/{uid}/][%d] deleteWebhookByIdNoContent ", 204)
}

func (o *DeleteWebhookByIDNoContent) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewDeleteWebhookByIDUnauthorized creates a DeleteWebhookByIDUnauthorized with default headers values
func NewDeleteWebhookByIDUnauthorized() *DeleteWebhookByIDUnauthorized {
	return &DeleteWebhookByIDUnauthorized{}
}

/*DeleteWebhookByIDUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type DeleteWebhookByIDUnauthorized struct {
	WWWAuthenticate string
}

func (o *DeleteWebhookByIDUnauthorized) Error() string {
	return fmt.Sprintf("[DELETE /webhook/{uid}/][%d] deleteWebhookByIdUnauthorized ", 401)
}

func (o *DeleteWebhookByIDUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewDeleteWebhookByIDForbidden creates a DeleteWebhookByIDForbidden with default headers values
func NewDeleteWebhookByIDForbidden() *DeleteWebhookByIDForbidden {
	return &DeleteWebhookByIDForbidden{}
}

/*DeleteWebhookByIDForbidden handles this case with default header values.

User not authorized or blocked
*/
type DeleteWebhookByIDForbidden struct {
	Payload *models.DeleteWebhookByIDForbiddenBody
}

func (o *DeleteWebhookByIDForbidden) Error() string {
	return fmt.Sprintf("[DELETE /webhook/{uid}/][%d] deleteWebhookByIdForbidden  %+v", 403, o.Payload)
}

func (o *DeleteWebhookByIDForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteWebhookByIDForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteWebhookByIDNotFound creates a DeleteWebhookByIDNotFound with default headers values
func NewDeleteWebhookByIDNotFound() *DeleteWebhookByIDNotFound {
	return &DeleteWebhookByIDNotFound{}
}

/*DeleteWebhookByIDNotFound handles this case with default header values.

Resource not found
*/
type DeleteWebhookByIDNotFound struct {
	Payload *models.DeleteWebhookByIDNotFoundBody
}

func (o *DeleteWebhookByIDNotFound) Error() string {
	return fmt.Sprintf("[DELETE /webhook/{uid}/][%d] deleteWebhookByIdNotFound  %+v", 404, o.Payload)
}

func (o *DeleteWebhookByIDNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteWebhookByIDNotFoundBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewDeleteWebhookByIDInternalServerError creates a DeleteWebhookByIDInternalServerError with default headers values
func NewDeleteWebhookByIDInternalServerError() *DeleteWebhookByIDInternalServerError {
	return &DeleteWebhookByIDInternalServerError{}
}

/*DeleteWebhookByIDInternalServerError handles this case with default header values.

Error
*/
type DeleteWebhookByIDInternalServerError struct {
	Payload *models.DeleteWebhookByIDInternalServerErrorBody
}

func (o *DeleteWebhookByIDInternalServerError) Error() string {
	return fmt.Sprintf("[DELETE /webhook/{uid}/][%d] deleteWebhookByIdInternalServerError  %+v", 500, o.Payload)
}

func (o *DeleteWebhookByIDInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.DeleteWebhookByIDInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
