// Code generated by go-swagger; DO NOT EDIT.

package webhook

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// NewPatchWebhookParams creates a new PatchWebhookParams object
// with the default values initialized.
func NewPatchWebhookParams() *PatchWebhookParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &PatchWebhookParams{
		APIVersion: aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewPatchWebhookParamsWithTimeout creates a new PatchWebhookParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewPatchWebhookParamsWithTimeout(timeout time.Duration) *PatchWebhookParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &PatchWebhookParams{
		APIVersion: aPIVersionDefault,

		timeout: timeout,
	}
}

// NewPatchWebhookParamsWithContext creates a new PatchWebhookParams object
// with the default values initialized, and the ability to set a context for a request
func NewPatchWebhookParamsWithContext(ctx context.Context) *PatchWebhookParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &PatchWebhookParams{
		APIVersion: apiVersionDefault,

		Context: ctx,
	}
}

// NewPatchWebhookParamsWithHTTPClient creates a new PatchWebhookParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewPatchWebhookParamsWithHTTPClient(client *http.Client) *PatchWebhookParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &PatchWebhookParams{
		APIVersion: apiVersionDefault,
		HTTPClient: client,
	}
}

/*PatchWebhookParams contains all the parameters to send to the API endpoint
for the patch webhook operation typically these are written to a http.Request
*/
type PatchWebhookParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion string
	/*UID
	  Alphanumeric ID of the webhook to edit.

	*/
	UID string
	/*Webhook
	  Webhook object

	*/
	Webhook *models.EditWebhook

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the patch webhook params
func (o *PatchWebhookParams) WithTimeout(timeout time.Duration) *PatchWebhookParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the patch webhook params
func (o *PatchWebhookParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the patch webhook params
func (o *PatchWebhookParams) WithContext(ctx context.Context) *PatchWebhookParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the patch webhook params
func (o *PatchWebhookParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the patch webhook params
func (o *PatchWebhookParams) WithHTTPClient(client *http.Client) *PatchWebhookParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the patch webhook params
func (o *PatchWebhookParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the patch webhook params
func (o *PatchWebhookParams) WithAPIVersion(aPIVersion string) *PatchWebhookParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the patch webhook params
func (o *PatchWebhookParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithUID adds the uid to the patch webhook params
func (o *PatchWebhookParams) WithUID(uid string) *PatchWebhookParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the patch webhook params
func (o *PatchWebhookParams) SetUID(uid string) {
	o.UID = uid
}

// WithWebhook adds the webhook to the patch webhook params
func (o *PatchWebhookParams) WithWebhook(webhook *models.EditWebhook) *PatchWebhookParams {
	o.SetWebhook(webhook)
	return o
}

// SetWebhook adds the webhook to the patch webhook params
func (o *PatchWebhookParams) SetWebhook(webhook *models.EditWebhook) {
	o.Webhook = webhook
}

// WriteToRequest writes these params to a swagger request
func (o *PatchWebhookParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param api-version
	if err := r.SetHeaderParam("api-version", o.APIVersion); err != nil {
		return err
	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if o.Webhook != nil {
		if err := r.SetBodyParam(o.Webhook); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
