// Code generated by go-swagger; DO NOT EDIT.

package number_search

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// GetNumbersearchReader is a Reader for the GetNumbersearch structure.
type GetNumbersearchReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *GetNumbersearchReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 200:
		result := NewGetNumbersearchOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 401:
		result := NewGetNumbersearchUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewGetNumbersearchForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewGetNumbersearchInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewGetNumbersearchOK creates a GetNumbersearchOK with default headers values
func NewGetNumbersearchOK() *GetNumbersearchOK {
	return &GetNumbersearchOK{}
}

/*GetNumbersearchOK handles this case with default header values.

A list of PhoneNumber objects
*/
type GetNumbersearchOK struct {
	Payload *models.GetNumbersearchOKBody
}

func (o *GetNumbersearchOK) Error() string {
	return fmt.Sprintf("[GET /numbersearch/][%d] getNumbersearchOK  %+v", 200, o.Payload)
}

func (o *GetNumbersearchOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNumbersearchOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNumbersearchUnauthorized creates a GetNumbersearchUnauthorized with default headers values
func NewGetNumbersearchUnauthorized() *GetNumbersearchUnauthorized {
	return &GetNumbersearchUnauthorized{}
}

/*GetNumbersearchUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type GetNumbersearchUnauthorized struct {
	WWWAuthenticate string
}

func (o *GetNumbersearchUnauthorized) Error() string {
	return fmt.Sprintf("[GET /numbersearch/][%d] getNumbersearchUnauthorized ", 401)
}

func (o *GetNumbersearchUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewGetNumbersearchForbidden creates a GetNumbersearchForbidden with default headers values
func NewGetNumbersearchForbidden() *GetNumbersearchForbidden {
	return &GetNumbersearchForbidden{}
}

/*GetNumbersearchForbidden handles this case with default header values.

User not authorized or blocked
*/
type GetNumbersearchForbidden struct {
	Payload *models.GetNumbersearchForbiddenBody
}

func (o *GetNumbersearchForbidden) Error() string {
	return fmt.Sprintf("[GET /numbersearch/][%d] getNumbersearchForbidden  %+v", 403, o.Payload)
}

func (o *GetNumbersearchForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNumbersearchForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewGetNumbersearchInternalServerError creates a GetNumbersearchInternalServerError with default headers values
func NewGetNumbersearchInternalServerError() *GetNumbersearchInternalServerError {
	return &GetNumbersearchInternalServerError{}
}

/*GetNumbersearchInternalServerError handles this case with default header values.

Error
*/
type GetNumbersearchInternalServerError struct {
	Payload *models.GetNumbersearchInternalServerErrorBody
}

func (o *GetNumbersearchInternalServerError) Error() string {
	return fmt.Sprintf("[GET /numbersearch/][%d] getNumbersearchInternalServerError  %+v", 500, o.Payload)
}

func (o *GetNumbersearchInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.GetNumbersearchInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
