// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// NewCreateSubaccountParams creates a new CreateSubaccountParams object
// with the default values initialized.
func NewCreateSubaccountParams() *CreateSubaccountParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &CreateSubaccountParams{
		APIVersion: &aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewCreateSubaccountParamsWithTimeout creates a new CreateSubaccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewCreateSubaccountParamsWithTimeout(timeout time.Duration) *CreateSubaccountParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &CreateSubaccountParams{
		APIVersion: &aPIVersionDefault,

		timeout: timeout,
	}
}

// NewCreateSubaccountParamsWithContext creates a new CreateSubaccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewCreateSubaccountParamsWithContext(ctx context.Context) *CreateSubaccountParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &CreateSubaccountParams{
		APIVersion: &apiVersionDefault,

		Context: ctx,
	}
}

// NewCreateSubaccountParamsWithHTTPClient creates a new CreateSubaccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewCreateSubaccountParamsWithHTTPClient(client *http.Client) *CreateSubaccountParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &CreateSubaccountParams{
		APIVersion: &apiVersionDefault,
		HTTPClient: client,
	}
}

/*CreateSubaccountParams contains all the parameters to send to the API endpoint
for the create subaccount operation typically these are written to a http.Request
*/
type CreateSubaccountParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion *string
	/*Subaccount
	  Subaccount object

	*/
	Subaccount *models.CreateAccount

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the create subaccount params
func (o *CreateSubaccountParams) WithTimeout(timeout time.Duration) *CreateSubaccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the create subaccount params
func (o *CreateSubaccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the create subaccount params
func (o *CreateSubaccountParams) WithContext(ctx context.Context) *CreateSubaccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the create subaccount params
func (o *CreateSubaccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the create subaccount params
func (o *CreateSubaccountParams) WithHTTPClient(client *http.Client) *CreateSubaccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the create subaccount params
func (o *CreateSubaccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the create subaccount params
func (o *CreateSubaccountParams) WithAPIVersion(aPIVersion *string) *CreateSubaccountParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the create subaccount params
func (o *CreateSubaccountParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithSubaccount adds the subaccount to the create subaccount params
func (o *CreateSubaccountParams) WithSubaccount(subaccount *models.CreateAccount) *CreateSubaccountParams {
	o.SetSubaccount(subaccount)
	return o
}

// SetSubaccount adds the subaccount to the create subaccount params
func (o *CreateSubaccountParams) SetSubaccount(subaccount *models.CreateAccount) {
	o.Subaccount = subaccount
}

// WriteToRequest writes these params to a swagger request
func (o *CreateSubaccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param api-version
		if err := r.SetHeaderParam("api-version", *o.APIVersion); err != nil {
			return err
		}

	}

	if o.Subaccount != nil {
		if err := r.SetBodyParam(o.Subaccount); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
