// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"

	strfmt "github.com/go-openapi/strfmt"

	models "github.com/karixtech/go-karix/models"
)

// CreateSubaccountReader is a Reader for the CreateSubaccount structure.
type CreateSubaccountReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *CreateSubaccountReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {

	case 201:
		result := NewCreateSubaccountCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil

	case 400:
		result := NewCreateSubaccountBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 401:
		result := NewCreateSubaccountUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 403:
		result := NewCreateSubaccountForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	case 500:
		result := NewCreateSubaccountInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result

	default:
		return nil, runtime.NewAPIError("unknown error", response, response.Code())
	}
}

// NewCreateSubaccountCreated creates a CreateSubaccountCreated with default headers values
func NewCreateSubaccountCreated() *CreateSubaccountCreated {
	return &CreateSubaccountCreated{}
}

/*CreateSubaccountCreated handles this case with default header values.

A subaccount object
*/
type CreateSubaccountCreated struct {
	Payload *models.CreateSubaccountCreatedBody
}

func (o *CreateSubaccountCreated) Error() string {
	return fmt.Sprintf("[POST /account/][%d] createSubaccountCreated  %+v", 201, o.Payload)
}

func (o *CreateSubaccountCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSubaccountCreatedBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSubaccountBadRequest creates a CreateSubaccountBadRequest with default headers values
func NewCreateSubaccountBadRequest() *CreateSubaccountBadRequest {
	return &CreateSubaccountBadRequest{}
}

/*CreateSubaccountBadRequest handles this case with default header values.

Error
*/
type CreateSubaccountBadRequest struct {
	Payload *models.CreateSubaccountBadRequestBody
}

func (o *CreateSubaccountBadRequest) Error() string {
	return fmt.Sprintf("[POST /account/][%d] createSubaccountBadRequest  %+v", 400, o.Payload)
}

func (o *CreateSubaccountBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSubaccountBadRequestBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSubaccountUnauthorized creates a CreateSubaccountUnauthorized with default headers values
func NewCreateSubaccountUnauthorized() *CreateSubaccountUnauthorized {
	return &CreateSubaccountUnauthorized{}
}

/*CreateSubaccountUnauthorized handles this case with default header values.

Authentication information is missing or invalid
*/
type CreateSubaccountUnauthorized struct {
	WWWAuthenticate string
}

func (o *CreateSubaccountUnauthorized) Error() string {
	return fmt.Sprintf("[POST /account/][%d] createSubaccountUnauthorized ", 401)
}

func (o *CreateSubaccountUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header WWW_Authenticate
	o.WWWAuthenticate = response.GetHeader("WWW_Authenticate")

	return nil
}

// NewCreateSubaccountForbidden creates a CreateSubaccountForbidden with default headers values
func NewCreateSubaccountForbidden() *CreateSubaccountForbidden {
	return &CreateSubaccountForbidden{}
}

/*CreateSubaccountForbidden handles this case with default header values.

User not authorized or blocked
*/
type CreateSubaccountForbidden struct {
	Payload *models.CreateSubaccountForbiddenBody
}

func (o *CreateSubaccountForbidden) Error() string {
	return fmt.Sprintf("[POST /account/][%d] createSubaccountForbidden  %+v", 403, o.Payload)
}

func (o *CreateSubaccountForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSubaccountForbiddenBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewCreateSubaccountInternalServerError creates a CreateSubaccountInternalServerError with default headers values
func NewCreateSubaccountInternalServerError() *CreateSubaccountInternalServerError {
	return &CreateSubaccountInternalServerError{}
}

/*CreateSubaccountInternalServerError handles this case with default header values.

Error
*/
type CreateSubaccountInternalServerError struct {
	Payload *models.CreateSubaccountInternalServerErrorBody
}

func (o *CreateSubaccountInternalServerError) Error() string {
	return fmt.Sprintf("[POST /account/][%d] createSubaccountInternalServerError  %+v", 500, o.Payload)
}

func (o *CreateSubaccountInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.CreateSubaccountInternalServerErrorBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
