// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"net/http"
	"time"

	"golang.org/x/net/context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubaccountByIDParams creates a new GetSubaccountByIDParams object
// with the default values initialized.
func NewGetSubaccountByIDParams() *GetSubaccountByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetSubaccountByIDParams{
		APIVersion: &aPIVersionDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubaccountByIDParamsWithTimeout creates a new GetSubaccountByIDParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubaccountByIDParamsWithTimeout(timeout time.Duration) *GetSubaccountByIDParams {
	var (
		aPIVersionDefault = string("1.0")
	)
	return &GetSubaccountByIDParams{
		APIVersion: &aPIVersionDefault,

		timeout: timeout,
	}
}

// NewGetSubaccountByIDParamsWithContext creates a new GetSubaccountByIDParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubaccountByIDParamsWithContext(ctx context.Context) *GetSubaccountByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetSubaccountByIDParams{
		APIVersion: &apiVersionDefault,

		Context: ctx,
	}
}

// NewGetSubaccountByIDParamsWithHTTPClient creates a new GetSubaccountByIDParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubaccountByIDParamsWithHTTPClient(client *http.Client) *GetSubaccountByIDParams {
	var (
		apiVersionDefault = string("1.0")
	)
	return &GetSubaccountByIDParams{
		APIVersion: &apiVersionDefault,
		HTTPClient: client,
	}
}

/*GetSubaccountByIDParams contains all the parameters to send to the API endpoint
for the get subaccount by Id operation typically these are written to a http.Request
*/
type GetSubaccountByIDParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion *string
	/*UID
	  Alphanumeric ID of the subaccount to get.

	*/
	UID string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subaccount by Id params
func (o *GetSubaccountByIDParams) WithTimeout(timeout time.Duration) *GetSubaccountByIDParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subaccount by Id params
func (o *GetSubaccountByIDParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subaccount by Id params
func (o *GetSubaccountByIDParams) WithContext(ctx context.Context) *GetSubaccountByIDParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subaccount by Id params
func (o *GetSubaccountByIDParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subaccount by Id params
func (o *GetSubaccountByIDParams) WithHTTPClient(client *http.Client) *GetSubaccountByIDParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subaccount by Id params
func (o *GetSubaccountByIDParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get subaccount by Id params
func (o *GetSubaccountByIDParams) WithAPIVersion(aPIVersion *string) *GetSubaccountByIDParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get subaccount by Id params
func (o *GetSubaccountByIDParams) SetAPIVersion(aPIVersion *string) {
	o.APIVersion = aPIVersion
}

// WithUID adds the uid to the get subaccount by Id params
func (o *GetSubaccountByIDParams) WithUID(uid string) *GetSubaccountByIDParams {
	o.SetUID(uid)
	return o
}

// SetUID adds the uid to the get subaccount by Id params
func (o *GetSubaccountByIDParams) SetUID(uid string) {
	o.UID = uid
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubaccountByIDParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.APIVersion != nil {

		// header param api-version
		if err := r.SetHeaderParam("api-version", *o.APIVersion); err != nil {
			return err
		}

	}

	// path param uid
	if err := r.SetPathParam("uid", o.UID); err != nil {
		return err
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
