// Code generated by go-swagger; DO NOT EDIT.

package accounts

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/swag"

	strfmt "github.com/go-openapi/strfmt"
)

// NewGetSubaccountParams creates a new GetSubaccountParams object
// with the default values initialized.
func NewGetSubaccountParams() *GetSubaccountParams {
	var (
		aPIVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetSubaccountParams{
		APIVersion: aPIVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		timeout: cr.DefaultTimeout,
	}
}

// NewGetSubaccountParamsWithTimeout creates a new GetSubaccountParams object
// with the default values initialized, and the ability to set a timeout on a request
func NewGetSubaccountParamsWithTimeout(timeout time.Duration) *GetSubaccountParams {
	var (
		aPIVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetSubaccountParams{
		APIVersion: aPIVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		timeout: timeout,
	}
}

// NewGetSubaccountParamsWithContext creates a new GetSubaccountParams object
// with the default values initialized, and the ability to set a context for a request
func NewGetSubaccountParamsWithContext(ctx context.Context) *GetSubaccountParams {
	var (
		apiVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetSubaccountParams{
		APIVersion: apiVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,

		Context: ctx,
	}
}

// NewGetSubaccountParamsWithHTTPClient creates a new GetSubaccountParams object
// with the default values initialized, and the ability to set a custom HTTPClient for a request
func NewGetSubaccountParamsWithHTTPClient(client *http.Client) *GetSubaccountParams {
	var (
		apiVersionDefault = string("1.0")
		limitDefault      = int64(10)
		offsetDefault     = int64(0)
	)
	return &GetSubaccountParams{
		APIVersion: apiVersionDefault,
		Limit:      &limitDefault,
		Offset:     &offsetDefault,
		HTTPClient: client,
	}
}

/*GetSubaccountParams contains all the parameters to send to the API endpoint
for the get subaccount operation typically these are written to a http.Request
*/
type GetSubaccountParams struct {

	/*APIVersion
	  API Version. If not specified your pinned verison is used.

	*/
	APIVersion string
	/*Limit
	  The numbers of items to return.

	*/
	Limit *int64
	/*Offset
	  The number of items to skip before starting to collect the result set.

	*/
	Offset *int64

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithTimeout adds the timeout to the get subaccount params
func (o *GetSubaccountParams) WithTimeout(timeout time.Duration) *GetSubaccountParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the get subaccount params
func (o *GetSubaccountParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the get subaccount params
func (o *GetSubaccountParams) WithContext(ctx context.Context) *GetSubaccountParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the get subaccount params
func (o *GetSubaccountParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the get subaccount params
func (o *GetSubaccountParams) WithHTTPClient(client *http.Client) *GetSubaccountParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the get subaccount params
func (o *GetSubaccountParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithAPIVersion adds the aPIVersion to the get subaccount params
func (o *GetSubaccountParams) WithAPIVersion(aPIVersion string) *GetSubaccountParams {
	o.SetAPIVersion(aPIVersion)
	return o
}

// SetAPIVersion adds the apiVersion to the get subaccount params
func (o *GetSubaccountParams) SetAPIVersion(aPIVersion string) {
	o.APIVersion = aPIVersion
}

// WithLimit adds the limit to the get subaccount params
func (o *GetSubaccountParams) WithLimit(limit *int64) *GetSubaccountParams {
	o.SetLimit(limit)
	return o
}

// SetLimit adds the limit to the get subaccount params
func (o *GetSubaccountParams) SetLimit(limit *int64) {
	o.Limit = limit
}

// WithOffset adds the offset to the get subaccount params
func (o *GetSubaccountParams) WithOffset(offset *int64) *GetSubaccountParams {
	o.SetOffset(offset)
	return o
}

// SetOffset adds the offset to the get subaccount params
func (o *GetSubaccountParams) SetOffset(offset *int64) {
	o.Offset = offset
}

// WriteToRequest writes these params to a swagger request
func (o *GetSubaccountParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// header param api-version
	if err := r.SetHeaderParam("api-version", o.APIVersion); err != nil {
		return err
	}

	if o.Limit != nil {

		// query param limit
		var qrLimit int64
		if o.Limit != nil {
			qrLimit = *o.Limit
		}
		qLimit := swag.FormatInt64(qrLimit)
		if qLimit != "" {
			if err := r.SetQueryParam("limit", qLimit); err != nil {
				return err
			}
		}

	}

	if o.Offset != nil {

		// query param offset
		var qrOffset int64
		if o.Offset != nil {
			qrOffset = *o.Offset
		}
		qOffset := swag.FormatInt64(qrOffset)
		if qOffset != "" {
			if err := r.SetQueryParam("offset", qOffset); err != nil {
				return err
			}
		}

	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
