// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// ArrayMetaResponseAllOf1 array meta response all of1
// swagger:model arrayMetaResponseAllOf1
type ArrayMetaResponseAllOf1 struct {

	// URL to fetch the next page of the object list
	// - `null` if there is no next page
	//
	Next *string `json:"next,omitempty"`

	// URL to fetch the previous page of the object list
	// - `null` if there is no previous page
	//
	Previous *string `json:"previous,omitempty"`

	// Total number of objects in all pages
	//
	Total int64 `json:"total,omitempty"`
}

// Validate validates this array meta response all of1
func (m *ArrayMetaResponseAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *ArrayMetaResponseAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *ArrayMetaResponseAllOf1) UnmarshalBinary(b []byte) error {
	var res ArrayMetaResponseAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
