// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/swag"
)

// EditAccountNumber edit account number
// swagger:model EditAccountNumber
type EditAccountNumber struct {

	// Display alias of this number for the account
	Alias string `json:"alias,omitempty"`

	// Webhook attached to this phone number which is triggered on an event
	// like incoming message.
	//
	WebhookUID *string `json:"webhook_uid,omitempty"`
}

// Validate validates this edit account number
func (m *EditAccountNumber) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *EditAccountNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *EditAccountNumber) UnmarshalBinary(b []byte) error {
	var res EditAccountNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
