// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetNumbersearchOKBody get numbersearch o k body
// swagger:model getNumbersearchOKBody
type GetNumbersearchOKBody struct {

	// meta
	Meta *ArrayMetaResponse `json:"meta,omitempty"`

	// objects
	Objects GetNumbersearchOKBodyObjects `json:"objects"`
}

// Validate validates this get numbersearch o k body
func (m *GetNumbersearchOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetNumbersearchOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetNumbersearchOKBody) UnmarshalBinary(b []byte) error {
	var res GetNumbersearchOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
