// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// GetWebhookOKBody get webhook o k body
// swagger:model getWebhookOKBody
type GetWebhookOKBody struct {

	// meta
	Meta *ArrayMetaResponse `json:"meta,omitempty"`

	// objects
	Objects GetWebhookOKBodyObjects `json:"objects"`
}

// Validate validates this get webhook o k body
func (m *GetWebhookOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *GetWebhookOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *GetWebhookOKBody) UnmarshalBinary(b []byte) error {
	var res GetWebhookOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
