// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MetaResponseWithBalanceAllOf1 meta response with balance all of1
// swagger:model metaResponseWithBalanceAllOf1
type MetaResponseWithBalanceAllOf1 struct {

	// available credits
	AvailableCredits string `json:"available_credits,omitempty"`

	// credits charged
	CreditsCharged string `json:"credits_charged,omitempty"`
}

// Validate validates this meta response with balance all of1
func (m *MetaResponseWithBalanceAllOf1) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *MetaResponseWithBalanceAllOf1) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaResponseWithBalanceAllOf1) UnmarshalBinary(b []byte) error {
	var res MetaResponseWithBalanceAllOf1
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
