// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/shopspring/decimal"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// MetaResponseWithBalance meta response with balance
// swagger:model MetaResponseWithBalance
type MetaResponseWithBalance struct {
	MetaResponse

	// available credits
	AvailableCredits decimal.Decimal `json:"available_credits,omitempty"`

	// credits charged
	CreditsCharged decimal.Decimal `json:"credits_charged,omitempty"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (m *MetaResponseWithBalance) UnmarshalJSON(raw []byte) error {
	// AO0
	var aO0 MetaResponse
	if err := swag.ReadJSON(raw, &aO0); err != nil {
		return err
	}
	m.MetaResponse = aO0

	// AO1
	var dataAO1 struct {
		AvailableCredits decimal.Decimal `json:"available_credits,omitempty"`

		CreditsCharged decimal.Decimal `json:"credits_charged,omitempty"`
	}
	if err := swag.ReadJSON(raw, &dataAO1); err != nil {
		return err
	}

	m.AvailableCredits = dataAO1.AvailableCredits

	m.CreditsCharged = dataAO1.CreditsCharged

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (m MetaResponseWithBalance) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 2)

	aO0, err := swag.WriteJSON(m.MetaResponse)
	if err != nil {
		return nil, err
	}
	_parts = append(_parts, aO0)

	var dataAO1 struct {
		AvailableCredits decimal.Decimal `json:"available_credits,omitempty"`

		CreditsCharged decimal.Decimal `json:"credits_charged,omitempty"`
	}

	dataAO1.AvailableCredits = m.AvailableCredits

	dataAO1.CreditsCharged = m.CreditsCharged

	jsonDataAO1, errAO1 := swag.WriteJSON(dataAO1)
	if errAO1 != nil {
		return nil, errAO1
	}
	_parts = append(_parts, jsonDataAO1)

	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this meta response with balance
func (m *MetaResponseWithBalance) Validate(formats strfmt.Registry) error {
	var res []error

	// validation for a type composition with MetaResponse
	if err := m.MetaResponse.Validate(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *MetaResponseWithBalance) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *MetaResponseWithBalance) UnmarshalBinary(b []byte) error {
	var res MetaResponseWithBalance
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
