// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PatchNumberNumOKBody patch number num o k body
// swagger:model patchNumberNumOKBody
type PatchNumberNumOKBody struct {

	// data
	Data *AccountNumber `json:"data,omitempty"`

	// meta
	Meta *ObjectMetaResponse `json:"meta,omitempty"`
}

// Validate validates this patch number num o k body
func (m *PatchNumberNumOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PatchNumberNumOKBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PatchNumberNumOKBody) UnmarshalBinary(b []byte) error {
	var res PatchNumberNumOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
