// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"
	"github.com/shopspring/decimal"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PhoneNumber Details of the phone number
// swagger:model PhoneNumber
type PhoneNumber struct {

	// Number with country code
	Number string `json:"number,omitempty"`

	// number type
	NumberType string `json:"number_type,omitempty"`

	// rate
	Rate *PhoneNumberRate `json:"rate,omitempty"`

	// region
	Region *PhoneNumberRegion `json:"region,omitempty"`

	// service
	Service *PhoneNumberService `json:"service,omitempty"`
}

// Validate validates this phone number
func (m *PhoneNumber) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateRate(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateRegion(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateService(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *PhoneNumber) validateRate(formats strfmt.Registry) error {

	if swag.IsZero(m.Rate) { // not required
		return nil
	}

	if m.Rate != nil {
		if err := m.Rate.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("rate")
			}
			return err
		}
	}

	return nil
}

func (m *PhoneNumber) validateRegion(formats strfmt.Registry) error {

	if swag.IsZero(m.Region) { // not required
		return nil
	}

	if m.Region != nil {
		if err := m.Region.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("region")
			}
			return err
		}
	}

	return nil
}

func (m *PhoneNumber) validateService(formats strfmt.Registry) error {

	if swag.IsZero(m.Service) { // not required
		return nil
	}

	if m.Service != nil {
		if err := m.Service.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("service")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNumber) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNumber) UnmarshalBinary(b []byte) error {
	var res PhoneNumber
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PhoneNumberRate phone number rate
// swagger:model PhoneNumberRate
type PhoneNumberRate struct {

	// Rate per part of an incoming message
	InboundSms decimal.NullDecimal `json:"inbound_sms,omitempty"`

	// Monthly rental rate for this number.
	// When the number is bought a prorated rental rate is deducted from balance
	//
	Rental decimal.Decimal `json:"rental,omitempty"`

	// One time setup fees for this number
	Setup decimal.Decimal `json:"setup,omitempty"`
}

// Validate validates this phone number rate
func (m *PhoneNumberRate) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNumberRate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNumberRate) UnmarshalBinary(b []byte) error {
	var res PhoneNumberRate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PhoneNumberRegion Details about which region this number belongs to
// swagger:model PhoneNumberRegion
type PhoneNumberRegion struct {

	// Country ISO of this number
	Country string `json:"country,omitempty"`
}

// Validate validates this phone number region
func (m *PhoneNumberRegion) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNumberRegion) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNumberRegion) UnmarshalBinary(b []byte) error {
	var res PhoneNumberRegion
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// PhoneNumberService Services available on this number
// swagger:model PhoneNumberService
type PhoneNumberService struct {

	// `true` if sms service is available on this number
	Sms bool `json:"sms,omitempty"`
}

// Validate validates this phone number service
func (m *PhoneNumberService) Validate(formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNumberService) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNumberService) UnmarshalBinary(b []byte) error {
	var res PhoneNumberService
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
