// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// PhoneNumberRate phone number rate
// swagger:model phoneNumberRate
type PhoneNumberRate struct {

	// Rate per part of an incoming message
	InboundSms *string `json:"inbound_sms,omitempty"`

	// Monthly rental rate for this number.
	// When the number is bought a prorated rental rate is deducted from balance
	//
	Rental string `json:"rental,omitempty"`

	// One time setup fees for this number
	Setup string `json:"setup,omitempty"`
}

// Validate validates this phone number rate
func (m *PhoneNumberRate) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *PhoneNumberRate) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *PhoneNumberRate) UnmarshalBinary(b []byte) error {
	var res PhoneNumberRate
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
