// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	strfmt "github.com/go-openapi/strfmt"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/swag"
)

// SendMessageAcceptedBody send message accepted body
// swagger:model sendMessageAcceptedBody
type SendMessageAcceptedBody struct {

	// meta
	Meta *MetaResponseWithBalance `json:"meta,omitempty"`

	// objects
	Objects SendMessageAcceptedBodyObjects `json:"objects"`
}

// Validate validates this send message accepted body
func (m *SendMessageAcceptedBody) Validate(formats strfmt.Registry) error {
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// MarshalBinary interface implementation
func (m *SendMessageAcceptedBody) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *SendMessageAcceptedBody) UnmarshalBinary(b []byte) error {
	var res SendMessageAcceptedBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
